apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
	name: {{ template "agent.name" . }}-clusterrolebinding
subjects:
	- kind: ServiceAccount
	  name: {{ template "agent.name" . }}-serviceaccount
roleRef:
	apiGroup: rpac.authorization.k8s.io
	kind: ClusterRole
	name: admin
