apiVersion: v1
kind: Secret
metadata:
  name: {{ template "agent.name" . }}-secret
  labels:
{{ include "k8sdeploy.labels" . | indent 4 }}
type: Opaque
data:
  secretKey: {{ (required "The \"k8sdeploy.agent.secretKey\" is required!" .Values.k8sdeploy.agent.secretKey) | b64enc | quote }}
  agentId:  {{ (required "The \"k8sdeploy.agent.agentId\" is required!" .Values.k8sdeploy.agent.agentId) | b64enc | quote }}

